services:
  db:
    image: postgres:latest
    env_file:
      - .env.local
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    restart: unless-stopped

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env.local
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    restart: unless-stopped

volumes:
  db_data:
