// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "surname", Type: field.TypeString, Size: 100},
		{Name: "number", Type: field.TypeInt},
		{Name: "gender", Type: field.TypeEnum, Enums: []string{"Male", "Female"}},
		{Name: "country", Type: field.TypeString, Size: 50},
		{Name: "dependants", Type: field.TypeInt, Default: 0},
		{Name: "birth_date", Type: field.TypeTime},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomersTable,
	}
)

func init() {
}
