// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"iohk-golang-backend-preprod/ent/customer"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomerCreate is the builder for creating a Customer entity.
type CustomerCreate struct {
	config
	mutation *CustomerMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (cc *CustomerCreate) SetName(s string) *CustomerCreate {
	cc.mutation.SetName(s)
	return cc
}

// SetSurname sets the "surname" field.
func (cc *CustomerCreate) SetSurname(s string) *CustomerCreate {
	cc.mutation.SetSurname(s)
	return cc
}

// SetNumber sets the "number" field.
func (cc *CustomerCreate) SetNumber(i int) *CustomerCreate {
	cc.mutation.SetNumber(i)
	return cc
}

// SetGender sets the "gender" field.
func (cc *CustomerCreate) SetGender(c customer.Gender) *CustomerCreate {
	cc.mutation.SetGender(c)
	return cc
}

// SetCountry sets the "country" field.
func (cc *CustomerCreate) SetCountry(s string) *CustomerCreate {
	cc.mutation.SetCountry(s)
	return cc
}

// SetDependants sets the "dependants" field.
func (cc *CustomerCreate) SetDependants(i int) *CustomerCreate {
	cc.mutation.SetDependants(i)
	return cc
}

// SetNillableDependants sets the "dependants" field if the given value is not nil.
func (cc *CustomerCreate) SetNillableDependants(i *int) *CustomerCreate {
	if i != nil {
		cc.SetDependants(*i)
	}
	return cc
}

// SetBirthDate sets the "birth_date" field.
func (cc *CustomerCreate) SetBirthDate(t time.Time) *CustomerCreate {
	cc.mutation.SetBirthDate(t)
	return cc
}

// SetID sets the "id" field.
func (cc *CustomerCreate) SetID(i int) *CustomerCreate {
	cc.mutation.SetID(i)
	return cc
}

// Mutation returns the CustomerMutation object of the builder.
func (cc *CustomerCreate) Mutation() *CustomerMutation {
	return cc.mutation
}

// Save creates the Customer in the database.
func (cc *CustomerCreate) Save(ctx context.Context) (*Customer, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *CustomerCreate) SaveX(ctx context.Context) *Customer {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *CustomerCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *CustomerCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *CustomerCreate) defaults() {
	if _, ok := cc.mutation.Dependants(); !ok {
		v := customer.DefaultDependants
		cc.mutation.SetDependants(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *CustomerCreate) check() error {
	if _, ok := cc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Customer.name"`)}
	}
	if v, ok := cc.mutation.Name(); ok {
		if err := customer.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Customer.name": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Surname(); !ok {
		return &ValidationError{Name: "surname", err: errors.New(`ent: missing required field "Customer.surname"`)}
	}
	if v, ok := cc.mutation.Surname(); ok {
		if err := customer.SurnameValidator(v); err != nil {
			return &ValidationError{Name: "surname", err: fmt.Errorf(`ent: validator failed for field "Customer.surname": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Number(); !ok {
		return &ValidationError{Name: "number", err: errors.New(`ent: missing required field "Customer.number"`)}
	}
	if v, ok := cc.mutation.Number(); ok {
		if err := customer.NumberValidator(v); err != nil {
			return &ValidationError{Name: "number", err: fmt.Errorf(`ent: validator failed for field "Customer.number": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Gender(); !ok {
		return &ValidationError{Name: "gender", err: errors.New(`ent: missing required field "Customer.gender"`)}
	}
	if v, ok := cc.mutation.Gender(); ok {
		if err := customer.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Customer.gender": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Customer.country"`)}
	}
	if v, ok := cc.mutation.Country(); ok {
		if err := customer.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Customer.country": %w`, err)}
		}
	}
	if _, ok := cc.mutation.Dependants(); !ok {
		return &ValidationError{Name: "dependants", err: errors.New(`ent: missing required field "Customer.dependants"`)}
	}
	if v, ok := cc.mutation.Dependants(); ok {
		if err := customer.DependantsValidator(v); err != nil {
			return &ValidationError{Name: "dependants", err: fmt.Errorf(`ent: validator failed for field "Customer.dependants": %w`, err)}
		}
	}
	if _, ok := cc.mutation.BirthDate(); !ok {
		return &ValidationError{Name: "birth_date", err: errors.New(`ent: missing required field "Customer.birth_date"`)}
	}
	if v, ok := cc.mutation.ID(); ok {
		if err := customer.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Customer.id": %w`, err)}
		}
	}
	return nil
}

func (cc *CustomerCreate) sqlSave(ctx context.Context) (*Customer, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *CustomerCreate) createSpec() (*Customer, *sqlgraph.CreateSpec) {
	var (
		_node = &Customer{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(customer.Table, sqlgraph.NewFieldSpec(customer.FieldID, field.TypeInt))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := cc.mutation.Name(); ok {
		_spec.SetField(customer.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := cc.mutation.Surname(); ok {
		_spec.SetField(customer.FieldSurname, field.TypeString, value)
		_node.Surname = value
	}
	if value, ok := cc.mutation.Number(); ok {
		_spec.SetField(customer.FieldNumber, field.TypeInt, value)
		_node.Number = value
	}
	if value, ok := cc.mutation.Gender(); ok {
		_spec.SetField(customer.FieldGender, field.TypeEnum, value)
		_node.Gender = value
	}
	if value, ok := cc.mutation.Country(); ok {
		_spec.SetField(customer.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := cc.mutation.Dependants(); ok {
		_spec.SetField(customer.FieldDependants, field.TypeInt, value)
		_node.Dependants = value
	}
	if value, ok := cc.mutation.BirthDate(); ok {
		_spec.SetField(customer.FieldBirthDate, field.TypeTime, value)
		_node.BirthDate = value
	}
	return _node, _spec
}

// CustomerCreateBulk is the builder for creating many Customer entities in bulk.
type CustomerCreateBulk struct {
	config
	err      error
	builders []*CustomerCreate
}

// Save creates the Customer entities in the database.
func (ccb *CustomerCreateBulk) Save(ctx context.Context) ([]*Customer, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Customer, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *CustomerCreateBulk) SaveX(ctx context.Context) []*Customer {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *CustomerCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *CustomerCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
